FROM python:3.11-slim

WORKDIR /app

# Expose the port FastAPI runs on
EXPOSE 8000

# Set environment variables
ENV PYTHONPATH=/app

# Copy the application
COPY . .

# Command to run when the container starts
CMD ["./entrypoint.sh"]